#!/bin/bash

function clean  {
	if [ -e "Main.class" ]
		then
		rm floor/*.class
		rm display/*.class
		rm *.class
	fi
}
function make {
	clean
	javac *.java
}
case $@ in
	"")
	if [ -e "Main.class" ] 
		then java Main
	else
		make
		java Main
	fi 
	;;
	"c")
	clean
	;;
	"m")
	make
	;;
esac
